### PR TITLE
Fix Ruby 3.0 failure from double splat operator

### PR DESCRIPTION
**Pull request by justingaylor**
### Describe the change

This PR fixes a Ruby 3.0 failure (warning in Ruby 2.7) when using double splat operator/keyword params similar to this fix:
https://github.com/piotrmurach/tty-command/commit/5f422f89dd4dbfa96ca849cf5f9dcc6cac8b19e8

When using Ruby 3+ on `tty`, we'll encounter this error (in `tty-command`) trying to make a new app:
```
$ teletype new my_app      
/Users/justin.gaylor/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/tty-command-0.9.0/lib/tty/command.rb:54:in `initialize': wrong number of arguments (given 1, expected 0) (ArgumentError)
	from /Users/justin.gaylor/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/tty-0.10.0/lib/tty/cmd.rb:33:in `new'
	from /Users/justin.gaylor/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/tty-0.10.0/lib/tty/cmd.rb:33:in `command'
	from /Users/justin.gaylor/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/tty-0.10.0/lib/tty/commands/new.rb:46:in `initialize'
	from /Users/justin.gaylor/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/tty-0.10.0/lib/tty/cli.rb:128:in `new'
	from /Users/justin.gaylor/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/tty-0.10.0/lib/tty/cli.rb:128:in `new'
	from /Users/justin.gaylor/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /Users/justin.gaylor/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/justin.gaylor/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /Users/justin.gaylor/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /Users/justin.gaylor/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/tty-0.10.0/exe/teletype:14:in `<top (required)>'
	from /Users/justin.gaylor/.asdf/installs/ruby/3.0.3/bin/teletype:25:in `load'
	from /Users/justin.gaylor/.asdf/installs/ruby/3.0.3/bin/teletype:25:in `<main>'
```

By fixing this issue in `tty-command` and bumping the version in `tty`, hopefully we'll be a step closer to being able to use `tty` with Ruby 3+. (There is a separate `"`*': negative argument (ArgumentError)"` issue that happens in `tty` after this is fixed, so I will look into that after this gem gets fixed up.)

For further on the exact issue, read [here](https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/). 

Also, unit tests also were updated for a separate issue. When there is a space in the path to the checked out repo base, specs fail due to `TTY::Command` invoking ruby scripts in numerous places without shell escaping. This is fixed so specs will run for everybody.

### Why are we doing this?

`tty-command` doesn't work on Ruby 3.0 or higher.

### Benefits

We can more easily move `tty-command` (and thus the greater `tty` toolkit) forward to Ruby 3! 🚀 

### Drawbacks

None.

### Requirements

- [X] Tests written & passing locally?
- [ ] Code style checked?
- [X] Rebased with `master` branch?
- [X] Documentation updated?
- [ ] Changelog updated?

### CODE REVIEW

**Comment by justingaylor** [comment]
I can try to fix up those RuboCop violations, but I think that will retrigger the `Metrics/LineLength: Line is too long.` violations again.

**Review by kigster — APPROVED** [review]
This seems pretty straightforward.

**Review by jonatas — APPROVED** [review]
Seems legit. Trying locally I got the same issue and it seems a good alternative to fix it.

**Review by piotrmurach — COMMENTED** [review]
Hi Justin 👋 

Thank you for looking into this issue and trying to resolve it. 🙏 

Unfortunately, I don't believe we should be reverting to options hash. This change was done a long time ago and anyone who has used this gem should've already adjusted to using keywords. I see options hash as an antipattern. I no longer design my gems this way and wish tty-command to follow. Going forward, my preference is to use explicit keyword names and have Ruby on my side. Therefore I don't believe anything to be broken and thus need fixing on Ruby 3.0 as far as the initialisation goes. 

As for the `tty` gem, it is broken in many ways. It is also not the way I wish to encourage building command-line applications. It was an early attempt and I'm working on overhauling the experience. First, I'll need to get other dependencies ready. What I'm trying to say is that we shouldn't worry about the impact on the tty.

Lastly, great find with escaping the path. However, I think we should fix it in the helper method to improve maintenance. I'd accept a PR specifically fixing only that if you have time.

**Pull request closed without merging**
